### ISSUE TITLE
Species Mistakes - remove/edit

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/ErrorLog#22]
Find and edit.
e.g. Hawaiian Goose ?
Chesnut Rail ?

**Comment by StuMackenzie** [comment]
Goose - project 63 deploy 12164

**Comment by cjardine-bsc** [comment]
Rail project 142 deploy 11620

**Comment by StuMackenzie** [comment]
see admin tool - https://sandbox.motus.org/data/admin/species to help identify questionable species. There are some duplicates based on subspecies, but cleaning those up will take a bit of research to figure out which is which, or letting the PI know so they can fix it.

**Comment by zcrysler** [comment]
Ground woodpeckers appear in 167. Virginia Eastern Red Bats.  I'm quite positive this was an error on tag registration, but they want to wait for confirmation from field techs that it wasn't a mistake during their data entry before I delete these deployments.
