### ISSUE TITLE
Mark receivers as mobile

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/ErrorLog#23]
Find and mark all manual/ship/plane/car receivers as mobile

**Comment by cjardine-bsc** [comment]
I've updated the database and set is_mobile to true for all cases where fixture_type is Plane or Ship. 
  
UPDATE [motus].[dbo].[sensor_deployments]
  SET is_mobile = 1 
  where fixture_type in ('Ship',  'Plane')

I also set is_mobile to false for all deployments with fixture type as 'Building','Dam','PopTower' or 'Tower'
  
  UPDATE [motus].[dbo].[sensor_deployments]
  SET is_mobile = 0 
  where fixture_type in ('Building','Dam','PopTower','Tower')

That leaves 263 deployments that are not assigned as mobile or not. 

I've added a check to the data validation procedure that asks user to populate whether their deployment is mobile or not.

**Comment by zcrysler** [comment]
I updated a bunch of receiver types and looked through for other mobile units.  I think all mobile units are now marked as such.  

I think it would be ok to also set "Existing" as FALSE for is_mobile.

Can deployments with fixture_type 'handheld' and 'automobile' also be is_mobile TRUE - I think you probably already did this

**Comment by cjardine-bsc** [comment]
I think we'd best leave it to users to update is_mobile for "existing" fixture types. I think you're right that it's probably fine, but users do weird things sometimes.... it will be listed in the data validation center. 

I'll add a data validation check that will return an error if is_mobile is false and fixture_type is handheld, aircraft, land-based vehicle or ship.
