### ISSUE TITLE
Missing data project 25

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/ErrorLog#26]
It seems there is missing data for project 25, specifically from receivers SG-1814BBBK3221, SG-1814BBBK0585, SG-1814BBBK0809, and SG-0414BBBK0236; deviceIDs 597, 591, 592, and 543 respectively.

There are only detections for the 2014 deployment of SG-1913BBBK3221 deviceID 592. Data does not exist in the hourly plots (https://sensorgnome.org/download/25/ OR https://sensorgnome.org/download/0), in the .motus files, or on any visualizations online eg. https://motus.org/data/projectReceiverDeployments?id=25, but at some point it was in the system: https://sensorgnome.org/User:kate/Furbish/2015

![2015_obrien_furbish_alltags_plot_sig_vs_time_by_id](https://user-images.githubusercontent.com/22080197/33574553-50b38b38-d8ee-11e7-959c-f1fa0f34b813.png)

**Comment by cjardine-bsc** [comment]
There are 10700 hits for those device ID's for deployments:

(3842,
3356,
2084,
4386,
2648,
3779)

Of those deployments 3779, 3842 and 4386 are deployments for project 25. 

However 3779 is the 2014 deployment you reference and it is responsible for ~10000 of the 10162 hits for these three deployments. 

The run data from those two deployments looks like so:

runID	batchIDbegin	tsBegin	tsEnd	done	motusTagID	ambigID	ant	len
18168008	79132	1497489210.1949	1497489251.52	1	23888	NULL	1	2
18168009	79132	1498865029.3593	1498865106.1635	1	25167	NULL	1	2
18168010	79132	1499274379.5329	1499274458.8242	1	25289	NULL	1	2
18170580	79181	1495451178.6003	1495451592.0949	1	23593	NULL	2	38
18170581	79181	1495590983.8537	1495591381.6208	1	0	-53	2	37
18170582	79181	1501704114.7226	1501704532.7061	1	24738	NULL	4	18
18170583	79181	1502323577.4155	1502323678.6598	1	24592	NULL	4	5
18170584	79181	1502323688.4615	1502323739.2422	1	24592	NULL	4	4
18170585	79181	1502323789.4056	1502324153.1384	1	24592	NULL	2	28
18170586	79181	1502324364.8245	1502324486.2733	1	24592	NULL	2	9
18170587	79181	1502324607.1032	1502324647.7931	1	24592	NULL	2	4

As you can see batchID 79132 (deviceID 591) only has hits of run length <= 2, and therefore would be excluded from the online summaries.  BatchID 79181 (deviceID 591, deployment 4386) should be included in the taghit summaries though and were not. Re-running the processing for this batch populated the taghits summary with those records. 

USE [motus]
GO

DECLARE	@return_value int

EXEC	@return_value = [dbo].[prTaghitsSummariesBatchID]
		@batch_id = 79181

SELECT	'Return Value' = @return_value

GO

I'm not clear why they were missing from the taghits summaries before now. Denis, I'm not sure if you have recently made any changes that might effect this? We may want to rerun the prTaghitsSummariesAll proc in live?

**Comment by zcrysler** [comment]
Does that also explain why those detections aren't in the .motus files?

**Comment by cjardine-bsc** [comment]
It does not. 

Was the data not in the .motus file accessed from our server or the one accessed from the cached versions on the website? There should be 149 hits returned for these receivers from the R package from our server. 

SELECT * FROM [motus_sandbox].[dbo].[vwR_Hits_for_receiver]
where batchID in (79132 , 79181 )

**Comment by zcrysler** [comment]
I got the .motus file from the website, and from the latest tagme() function, neither have batchIDs 79181 or 79132

**Comment by zcrysler** [comment]
I can send an rds file separately for 2015 detections on SG-1814BBBK0585 which would correspond to deployment 2462, deviceID 591, it doesn't include batchID though

**Comment by cjardine-bsc** [comment]
The data from 591 is missing from both John's server and ours, so the problem is not with the import process to our server from Johns. 

This data may be part of a batched that failed to process completely and therefore might not have been uploaded to the simcoe server by John in August. When John does the next push of data we'll check to see if this information is included.
