### ISSUE TITLE
Potential missing detection

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/ErrorLog#28]
Detection of MotusTagID 24109 exists on the hourly plot (https://sensorgnome.org/download/150/SG-1215BBBK0682-2017_COAST_GEORG_ARRAY_GA_OSS_DOCK_hourly_tags.pdf)  but does not exist in current .motus data.  The receiver is ReceiverID 2090, SG-1215BBBK0682 and data was submitted in May.

Is this missing data or is it a case of a single detection being filtered out?

**Comment by cjardine-bsc** [comment]
So, yes this data is also missing from the database. The below query returns zero results. 

SELECT *
  FROM [motus].[dbo].[sg_runs]
  where motusTagID = 24109  and batchIDbegin in (77241,77240,77239,77238,77237)

But I think there is a problem beyond that. 

There are 5 batches from this receiver from May to September 2017

batchID	motusDeviceID	Day start day end numHits
77237	840	2017-05-22 15:27:03.687 	2017-06-05 13:02:16.197   	12
77238	840	2017-06-05 15:57:14.820	        2017-06-26 16:47:11.433	       10
77239	840	2017-06-26 16:48:36.877	        2017-07-17 12:32:43.843 	6
77240	840	2017-07-17 12:33:58.537	        2017-08-29 12:29:07.690	       109
77241	840	2017-08-29 12:29:52.897	        2017-09-07 19:47:05.063	        10

And 8 tags that were detected on those batches with len > 2

SELECT * FROM [motus].[dbo].[sg_runs]
 where batchIDbegin in (77241,77240,77239,77238,77237) and len > 2 

MotusTagIDs:
23596
25174
24700
25267
**23602**
25326
25289
**23598**

Whereas the plot you provide has 14 tags. Of the eight tags above two (**s) are not on the hourly plot. 

If we look at all tags detected during these batches (not filtered by run length), there are 33 different tags. Only 14 of which are on the hourly plot.

SELECT distinct motusTagID 
  FROM [motus].[dbo].[sg_runs]
  where batchIDbegin in (77241,77240,77239,77238,77237) 

I don't have an explanation for any of this yet, except to say that yes, there is a discrepancy between the data we have in the motus database and that available in the hourly plot for this receiver.
