### ISSUE TITLE
Missing metadata/receiver project 92

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/ErrorLog#32]
Project 92

The user reported that 
1. they have data in their static files for receivers SG-1315BBBK0085 deviceID 969, and SG-1315BBBK0143 deviceID 965, but almost all corresponding receiver fields are displayed as NA.  They only know the detections belong to those receivers is from the sporadic gps location data.  
2. they have no data for SG-5113BBBK3115 deviceID 330, I can see from John's hourly plots that that receiver does have detection data that was processed and includes a number of detections for their tags: https://sgdata.motus.org/download/1/SG-5113BBBK3115-2017_Motus_Guelph_Lake_CA_hourly_tags.pdf

attempting to load their static files and download all these .motus files for project and receivers is not cooperating through R and overheating my computer  - Catherine, can you see why they aren't getting full metadata, and where the missing receiver 330 data is?

**Comment by cjardine-bsc** [comment]
I downloaded their project through tagme and there are lots of hits from those device IDs in their file. 

There file is very large, maybe worth checking with them that it completely downloaded from Tagme?

**Comment by zcrysler** [comment]
In their static file, there are NAs for quite a lot of receiver metadata, including serial number, some examples:
runID 21312872, batchID 114142
runID 21258603, batchID 113516
runID 20756567, batchID 108249

Do those exist with metadata in the tagme() files?

**Comment by cjardine-bsc** [comment]
Okay, well that data is in the tagme() file. I don't know why it's missing from the static file, but I don't know that I'm going to worry too much about it at this point given that we'll stop supporting the static files shortly.
