### ISSUE TITLE
Updating incorrect Tag_Ids in sg_runs

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/ErrorLog#33]
In project 14, there are two tags that were registered twice. 

24642 and 26703
26012 and 26706

Tag_ids 24642 ,26012 are the tag_ids that the user would like to keep. Deployments have been created for these tags. 

Tags 26706 and26703 need to be deleted as they are duplicates with the exact same properties as 24642  and 26012. The user has confirmed that these two tags do not exist. 

However, tagfinder has assigned  hits to these two tags that need to be deleted. 

SELECT  [runID],[motusTagID],dbo.ts2datetime([tsBegin]),dbo.ts2datetime([tsEnd])
  FROM [motus].[dbo].[sg_runs]
  where motusTagID in (24642 ,26012 ,26706,26703)
  order by tsbegin

These runs are all assigned to tags 26706 and 26703. These runs all occur before the deployment start dates for tags 24642 and 26012. 

These runs are tests of the tag from before they are deployed. Tagfinder is looking at these hits and seeing what tags match. Because one of the two matching tags has a deployment start date after the date of the run it is excluded and the hits are being assigned unambiguously to the incorrect duplicate tag. 

The solution to this specific problem is simple, I just need to update the motusTagID in sg_runs to the correct non-duplicate tag and then delete the duplicate tags from the tag table. However I'm concerned that this will cause issues of primary key violations if we ever do a complete wipe and replace of the sg_ tables from John's server, since these tag_ids will no longer exist in our DB. 

This links into the need for us to dynamically assign tag_ids to runs on our end, both to fix errors like this and to resolve ambiguities based on changing metadata. To do so, we need to receive a list of tag properties associated with a run from John's server (mfg_id, period, frequency).

**Comment by cjardine-bsc** [comment]
Same problem for the tags below. There are pre-deployment test detections assigned to these tags. (March 2017 and some from September 2017).  Marked as deprecated for now. 

From Zoe: 

Project 19: there is a set of tags (512-521) that appear twice, once registered in 2016, and next registered in 2017.  Both sets have identical deployments (all deployed in 2017).  I think what happened here is that the same tags were registered twice, the user input deployment metadata once, forgot they already had, and input it again for the other registrations after seeing them blank.  The user has confirmed that the tags registered in 2016 were not deployed in 2016, and that there was only ever one set of tags 512-521.  Long story short, I need one set of those deleted forever because they were duplicate registrations and there was only ever 1 physical tag for each pair. Hopefully this jives with the detection data
 
motusTagIDs to delete:
23194
23195
23196
23197
23198
23199
23200
23201
23202
23203

**Comment by zcrysler** [comment]
any further thoughts on this?

**Comment by cjardine-bsc** [comment]
Its parked for the moment, it shouldn't impact the users in any way at this point, as the data is test data.

**Comment by zcrysler** [comment]
Two more duplicated tag registrations to delete for project 123: motusTagIDs 27539 and 27540.

**Comment by zcrysler** [comment]
And another duplicate pair in project 113 - tag IDs 27614 and 27616. 27614 can be deleted.

**Comment by zcrysler** [comment]
duplicates in project 177: 27774 and DELETE 27486

EXECprMergeTags tagToKeep , tagToDelete:
EXEC	prMergeTags	27214	,	27541
EXEC	prMergeTags	27215	,	27542
EXEC	prMergeTags	27216	,	27543
EXEC	prMergeTags	27217	,	27544
EXEC	prMergeTags	27218	,	27545
EXEC	prMergeTags	27219	,	27546
EXEC	prMergeTags	27220	,	27547
EXEC	prMergeTags	27221	,	27548
EXEC	prMergeTags	27222	,	27549
EXEC	prMergeTags	27223	,	27550
EXEC	prMergeTags	27224	,	27551
EXEC	prMergeTags	27225	,	27552
EXEC	prMergeTags	27226	,	27553
EXEC	prMergeTags	27227	,	27554
EXEC	prMergeTags	27228	,	27555
EXEC	prMergeTags	27229	,	27556
EXEC	prMergeTags	27230	,	27557
EXEC	prMergeTags	27231	,	27558
EXEC	prMergeTags	27232	,	27559
EXEC	prMergeTags	27233	,	27560
EXEC	prMergeTags	27234	,	27561
EXEC	prMergeTags	27235	,	27562
EXEC	prMergeTags	27236	,	27563
EXEC	prMergeTags	27237	,	27564
EXEC	prMergeTags	27238	,	27565
EXEC	prMergeTags	27239	,	27566
EXEC	prMergeTags	27240	,	27567
EXEC	prMergeTags	27241	,	27568
EXEC	prMergeTags	27242	,	27569
EXEC	prMergeTags	27243	,	27570
EXEC	prMergeTags	27244	,	27571
EXEC	prMergeTags	27245	,	27572
EXEC	prMergeTags	27246	,	27573
EXEC	prMergeTags	27247	,	27574
EXEC	prMergeTags	27248	,	27575
EXEC	prMergeTags	27249	,	27576
EXEC	prMergeTags	27250	,	27577
EXEC	prMergeTags	27251	,	27578
EXEC	prMergeTags	27252	,	27579
EXEC	prMergeTags	27253	,	27580
EXEC	prMergeTags	27254	,	27581
EXEC	prMergeTags	27255	,	27582
EXEC	prMergeTags	27256	,	27583
EXEC	prMergeTags	27257	,	27584
EXEC	prMergeTags	27258	,	27585
EXEC	prMergeTags	27259	,	27586
EXEC	prMergeTags	27260	,	27587
EXEC	prMergeTags	27261	,	27588
EXEC	prMergeTags	27262	,	27589
EXEC	prMergeTags	27263	,	27590
EXEC	prMergeTags	27264	,	27591
EXEC	prMergeTags	27265	,	27592
EXEC	prMergeTags	27266	,	27593
EXEC	prMergeTags	27267	,	27594
EXEC	prMergeTags	27268	,	27595
EXEC	prMergeTags	27269	,	27596
EXEC	prMergeTags	27270	,	27597
EXEC	prMergeTags	27271	,	27598
EXEC	prMergeTags	27272	,	27599
EXEC	prMergeTags	27273	,	27600
EXEC	prMergeTags	27274	,	27601
EXEC	prMergeTags	27275	,	27602
EXEC	prMergeTags	27276	,	27603
EXEC	prMergeTags	27277	,	27604
EXEC	prMergeTags	27283	,	27605
EXEC	prMergeTags	27284	,	27606
EXEC	prMergeTags	27285	,	27607
EXEC	prMergeTags	27286	,	27608
EXEC	prMergeTags	27287	,	27609
EXEC	prMergeTags	27288	,	27610
EXEC	prMergeTags	27289	,	27611
EXEC	prMergeTags	27290	,	27612
EXEC	prMergeTags	27291	,	27613
