### ISSUE TITLE
missing motusTagID

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/ErrorLog#37]
downloading for receiver lotek-223 using tagme(), there are a number of detections with motusTagID = 0, and all other tag metadata as NA.  

eg. runIDs 428283, 428285, 428339, all from batchID 365

**Comment by cjardine-bsc** [comment]
MotusTagID was being left as zero in vwR_Runs_for_receiver and therefore vwR_Tags_for_ambiguities was not being downloaded.

Changed vwR_Runs_for_receiver to: 

case when a.ambigID IS NULL THEN a.motusTagID else a.ambigID END as motusTagID

Tested and working.
