### ISSUE TITLE
Negative port #s

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/ErrorLog#38]
Some detection data is coming in with port listed as -1.  An example is receiver lotek-163, detections occur during deployments.  This apparently happens fairly often for data in project 74.  Happens in static and tagme() files

Any idea why this would happen, and if there's a way to determine actual port?

**Comment by cjardine-bsc** [comment]
Huh. This is coming in the tables imported from John. Looks like some issue on the data processing side. Maybe he's not been able to pull the portIDs from these files? 

~51k runs do not have port IDs in sg_runs 

SELECT count(*)
  FROM [motus].[dbo].[sg_runs]
  where ant < 0

**Comment by zcrysler** [comment]
From John:
Antenna "-1" represents the "A1+A2+A3+A4" compound antenna which is sometimes 
reported in Lotek .DTA file detections.  I'd guess it means the receiver has 
combined signal from 4 antennas to detect the tag, but I don't know the details
