### ISSUE TITLE
tellme() returning error for non-admin user

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/ErrorLog#39]
tellme("SG-4001BBBK2230", new = TRUE) provides an output when I run it with my login, but when the same code is run and I'm logged in as userID 230 I get "Error: Internal Server Error".  Same happens with SG-4001BBBK2230, but for some reason Lotek-6448 is fine.  This is project 14

**Comment by pmorrill** [comment]
The device id of this recv is 181. A quick query shows that it is linked to 4 different projects! (45,83,15,14). 

SELECT b.project_id FROM sensors_hash_keys a JOIN sensors b ON a.receiverID = b.receiverID WHERE a.id = 181

I'd say that we don't handle this very well when we verify access to the recv, which checks only the first project ID it encounters in that result set. I can change the verification to look for access to at least one of the projects returned. Testing it right now.

But if this is the primary issue, then she should also not be able to run tagme on that receiver......

**Comment by zcrysler** [comment]
Any update on this? There are two users asking for data from this project for two separate analyses
SG-2616BBBK1111 is also an issue in project 14.  They can't run tagme() or tellme() on these receivers.

**Comment by pmorrill** [comment]
Can you try it against the beta server, signed in as one of the pi's? It needs testing there, then we can plan for a push to live.

**Comment by zcrysler** [comment]
library(devtools)
install_github("motusWTS/motus@staging", force = TRUE)
install_github("motusWTS/motusClient@staging", force = TRUE)
library(motus)

setwd("C:/Users/cryslerz/Documents/motusDownloads")
projnum = "SG-4001BBBK2230"
tagme(projnum, new = TRUE, update = TRUE)

Error: Internal Server Error

Logging in as userID 230

Is that the proper way to test against beta?  with the staging branch of motus and motusClient?

**Comment by pmorrill** [comment]
We need to get Denis to confirm - I am out of touch with the specifics of the r-client branches. It used to tell you what server it was connecting to just before it tried to get data. But that might have been removed.

**Comment by denislepage** [comment]
Staging branch is now reverted to main database.

You’d have to go in R Studio, change the URL in z.onload.R in the staging branch, rebuild the package and try again.

**Comment by denislepage** [comment]
I have changed the staging branch of motusClient to point back to beta.

**Comment by zcrysler** [comment]
running the same code I'm still not able to run tagme() or tellme() with userID 230:

library(devtools)
install_github("motusWTS/motus@staging", force = TRUE)
install_github("motusWTS/motusClient@staging", force = TRUE)
library(motus)

setwd("C:/Users/cryslerz/Documents/motusDownloads")
projnum = "SG-4001BBBK2230"
tagme(projnum, new = TRUE, update = TRUE)

Error: Internal Server Error

**Comment by pmorrill** [comment]
I will grab the r-client and try this today. The original fix is in the code......

**Comment by pmorrill** [comment]
When I try to update my r client in R-Studio (using the series of commands Zoe lists above) it fails. This used to work fine, but now the following:

------------
Loading required package: RSQLite
Error: package or namespace load failed for ‘RSQLite’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘tibble’
------------

I tried updating my devtools - no improvement, Suggestions?

**Comment by pmorrill** [comment]
Zoe: I pointed my r-client (latest version) at the beta server for testing . I am not able to log in as Pam - she must have updated her password. But I signed in as rgray - project 45 also shares this recv - and was able to run 

# tellme("SG-4001BBBK2230")

with results.

Same on the alpha server. However, project 45 is not the best test to use since it would be the first one in the list returned by the auth device id query, so the verification would pass for Gray.

Can you send me Pam's password by direct email (don't put it in git)

**Comment by pmorrill** [comment]
I have a fix for this. The tellme function was OK, but tagme was still failing: when the batch id was passed in to get runs.

The fix went into the master and beta6 branches a few moments ago, so will appear in beta and sandbox tomorrow.

**Comment by pmorrill** [comment]
Zoe: I have run one test this AM, successfully. The tagme function appears to be working on the beta server, for this receiver, when signed in as Pam. Are you able to test against the beta server? It would be good for you to verify this.

**Comment by denislepage** [comment]
The motusClient staging branch is pointing to beta, I believe.

**Comment by zcrysler** [comment]
I'm still having problems.  I've tried downloading from scratch as Pam, and also just with an update to an existing receiver:

library(devtools)
install_github("motusWTS/motus@staging", force = TRUE)
install_github("motusWTS/motusClient@staging", force = TRUE)
library(motus)

> setwd("C:/Users/cryslerz/Documents/motusDownloads")
## update to an EXISTING .motus file
> projnum = "SG-2616BBBK1111"
> tagme(projnum, update = TRUE)
Please enter a value for login name at motus.org
==> 
pam.loring
Please enter a value for password at motus.org
==> 
***

Got 26 batch records
Error: Internal Server Error

## create a NEW .motus file
> projnum = "SG-4001BBBK2230"
> tagme(projnum, new = TRUE, update = TRUE)

updateMotusDb started (9 rows)
 - Create new view allambigs that converts ambig columns into rows
 - remove previous version of alltagswithambigs view
 - Remove empty gps detections
 - Add a new column "siteName" to table "recvDeps".Error in rsqlite_send_query(conn@ptr, statement) : 
  duplicate column name: siteName

 - Remove previous version of alltags
 - Create new version of alltags that includes additional deployment fields
 - Create (or modify previous version of) filters
 - Create (or modify previous version of) runsFilters
 - Create new table for custom tag metadataError in rsqlite_send_query(conn@ptr, statement) : not an error



Got 36 batch records
Error: Internal Server Error

## tellme() is working
> tellme(projnum)
   numHits   numBytes numRuns numBatches numGPS
1 13631719 1276246931  145186         36   7589

## tagme() works logged in as myself
> motusLogout()

   Salut - bye bye!

> tagme(projnum, new = TRUE, update = TRUE)
Please enter a value for login name at motus.org
==> 
zcrysler
Please enter a value for password at motus.org
==> 
***

Got 36 batch records

Got 26 runs starting at 0 for batch 32620                 
Got 481 hits starting at 0 for batch 32620                
Got 783 pulse counts for batch 32620                
Batch 32620 completed

**Comment by pmorrill** [comment]
Can you try again? I messed up and did not push the code change up to beta6 last night. I just did that, and Jeremy re-deployed. I think it is working now!

**Comment by zcrysler** [comment]
It works!

**Comment by denislepage** [comment]
The live branch was pushed earlier this afternoon.
