### ISSUE TITLE
Additional metadata fields not loading

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/ErrorLog#40]
Project 38 has additional tag metadata fields as entered by the user (eg. capture_time, release_date etc.), you can see them when you download the tag metadata through the website, but they don't load through tagme() or with forceMeta = TRUE.  Is this on purpose/is there a way for users to get any additional metadata fields without downloading a separate file from the website and merging with their .motus file?

**Comment by denislepage** [comment]
These are stored in a distinct table, and probably need their own API entry and process. The following steps would be necessary. I think they would be relatively simple to implement.

- [ ] add new table in motusClient and in motus hook function (updateMotusDb). [Denis]
- [ ] create new view vwR_Metadata_for_tags_properties  [Denis] (now done in both sandbox and motus)
- [ ] modify Motus API to package the new table within the returned payload. [Paul]
- [ ] ensure that motus securable permissions are used appropriately (tags_deployments_custom, I believe). These are part of the advanced metadata, which I believe are more restricted than the standard metadata by default.  [Denis, Paul]
- [ ] modify the motusClient package to read and insert the new payload into new table.  [Denis]

**Comment by pmorrill** [comment]
New functionality is in master and beta1 branches.

**Comment by denislepage** [comment]
I have now made the last changes needed to make this work. This is done in the staging branches of motus and motusClient. I have changed motusClient to point to the beta server for now.

Things seem to work as expected. I also tried with a few different projects and logins to make sure that permissions were respected. That seems ok as well. We may need to be a bit more testing.

If you do metadata(sql) from an admin account, you should get 3660 entries in tagProps. Less if you do it as a user. Project 38 should have 2489 properties.

```

library(devtools)
install_github("motusWTS/motusClient@staging")
install_github("motusWTS/motus@staging")
library(motus)
projID = 38
motus.sql = tagme(projID, dir="data", new=TRUE, update=FALSE)
# check that the database new contains tagProps table
motus.sql
metadata(motus.sql)

```

**Comment by denislepage** [comment]
Of the fields in the view, are you leaving out projectID, accessLevel and is_private_tag? TagID technically probably doesn't need to be there, but I am thinking I will leave it in. I have now created a process in the R package to accept those data, but the projectID, accessLevel and private fields are not included (will be  ignored if they are in the payload).

**Comment by pmorrill** [comment]
The packaging function automatically scrubs out 'accessLevel' and any field name beginning with 'is_private_'

But I can have it exclude other field fields specific to this query (such as tagID). As you say, projectID is redundant since we have the deployment id to link back to project. I will scrub it; just let me know if you want the tagID removed as well.

**Comment by denislepage** [comment]
We’ll leave tagID in.

**Comment by zcrysler** [comment]
working in the staging branch

**Comment by denislepage** [comment]
Cool. As soon as we can push the new server features to live, I can make the changes in the packages.

That is already part of beta5, so that can be done very shortly, and not have to wait for beta6.

Denis
