### ISSUE TITLE
Loring - Missing data

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/ErrorLog#5]
Report incomplete. Need to get specifics.

Project: Loring

Problem: PIPL TagIDs 435,437, and 441 (need MotusIDs) no being detected on MNYN tower. Possibly due to similar Lotek issue as Ohio State.

**Comment by zcrysler** [comment]
A number of tags are missing from Loring receivers, including a lot from projects 29 R5_SALS, 33 Ernts, and 25 obrien that were tagged in the area and had lots of detections on Loring receivers in past years.
